Repository googleapis/langchain-google-cloud-sql-mysql-python, pull requests merged in 2024-02, with the labels that each got.

#14 feat: Add document saver class and support save/load/delete user journeys.
  src/langchain_google_cloud_sql_mysql/__init__.py
  src/langchain_google_cloud_sql_mysql/mysql_engine.py
  src/langchain_google_cloud_sql_mysql/mysql_loader.py
  tests/integration/test_mysql_loader.py
  tests/unit/test_doc2row.py
Labels: api: cloudsql-mysql

#17 feat: support basic user/password auth with `MySQLEngine`
  integration.cloudbuild.yaml
  src/langchain_google_cloud_sql_mysql/mysql_engine.py
  tests/integration/test_mysql_engine.py
  tests/unit/test_engine.py
Labels: api: cloudsql-mysql

#16 feat: Add document saver class and support save/load/delete user journey
  src/langchain_google_cloud_sql_mysql/__init__.py
  src/langchain_google_cloud_sql_mysql/mysql_engine.py
  src/langchain_google_cloud_sql_mysql/mysql_loader.py
  tests/integration/test_mysql_loader.py
  tests/unit/test_doc2row.py
Labels: api: cloudsql-mysql

#20 chore: add helper for creating chat message table
  src/langchain_google_cloud_sql_mysql/mysql_chat_message_history.py
  src/langchain_google_cloud_sql_mysql/mysql_engine.py
  tests/integration/test_mysql_chat_message_history.py
Labels: api: cloudsql-mysql

#21 docs: add chat message history docs
  docs/chat_message_history.ipynb
Labels: api: cloudsql-mysql

#19 feat: support saving with customized content column and saving/loading with non-default metadata JSON column.
  src/langchain_google_cloud_sql_mysql/mysql_engine.py
  src/langchain_google_cloud_sql_mysql/mysql_loader.py
  tests/integration/test_mysql_loader.py
  tests/unit/test_doc2row.py
Labels: type: feature request, api: cloudsql-mysql

#22 chore(ci): Update repo files
  pyproject.toml
  src/langchain_google_cloud_sql_mysql/__init__.py
  src/langchain_google_cloud_sql_mysql/version.py
Labels: api: cloudsql-mysql

#18 docs: add docloader codelab
  README.md
  docs/document_loader.ipynb
Labels: type: feature request, api: cloudsql-mysql

#25 feat: add user_agent to client
  pyproject.toml
  src/langchain_google_cloud_sql_mysql/mysql_engine.py
  src/langchain_google_cloud_sql_mysql/version.py
Labels: api: cloudsql-mysql

#23 chore(ci): Add kokoro pipeline for release and docs
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/populate-secrets.sh
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/requirements.in
  .kokoro/requirements.txt
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
Labels: api: cloudsql-mysql

#24 chores(ci): cleanup naming
  src/langchain_google_cloud_sql_mysql/__init__.py
  src/langchain_google_cloud_sql_mysql/chat_message_history.py
  src/langchain_google_cloud_sql_mysql/engine.py
  src/langchain_google_cloud_sql_mysql/loader.py
  tests/unit/test_doc2row.py
Labels: api: cloudsql-mysql

#28 chore: cleanup doc
  docs/chat_message_history.ipynb
  docs/document_loader.ipynb
Labels: api: cloudsql-mysql

#31 chore: clean up repo
  .github/.Owlbot.lock.yaml
  .github/auto-approve.yml
  .github/renovate.json5
  .github/sync-repo-settings.yaml
  .github/workflows/lint.yml
  .gitignore
  MANIFEST.in
  README.md
  integration.cloudbuild.yaml
  owlbot.py
  pyproject.toml
  requirements.txt
  src/langchain_google_cloud_sql_mysql/py.typed
Labels: api: cloudsql-mysql

#33 docs: add MySQLChatMessageHistory to readme
  README.md
Labels: api: cloudsql-mysql, tests: run

#34 chore: add langchain link to readme
  README.md
Labels: api: cloudsql-mysql

#35 chore(ci): fix required tests
  .github/renovate.json5
  .github/sync-repo-settings.yaml
Labels: api: cloudsql-mysql

#36 chore: update release pipeline requirements
  .kokoro/requirements.txt
Labels: api: cloudsql-mysql

#37 chore: add build module to release pipeline
  .kokoro/requirements.txt
Labels: api: cloudsql-mysql

#38 chore: regenerate kokoro deps
  .kokoro/requirements.txt
Labels: api: cloudsql-mysql

#39 chore: add deps to kokoro release jobs
  .kokoro/requirements.in
  .kokoro/requirements.txt
Labels: api: cloudsql-mysql

#40 chore: add deps to kokoro release jobs
  .kokoro/requirements.in
  .kokoro/requirements.txt
Labels: api: cloudsql-mysql
